### ISSUE TITLE
RuntimeError: The size of tensor a (16) must match the size of tensor b (64) at non-singleton dimension 0

### ISSUE THREAD

**Issue by haiahaiah** [DevSinghSachan/syntax-augmented-bert#2]
Hi, I'm studying your work which is very interesting. But when I ran your code, it showed the first problem as follows:

_"StopIteration: Caught StopIteration in replica 0 on device 0."_

and I found it may be the version of torch according to [here](https://github.com/facebookresearch/vilbert-multi-task/issues/57). So I changed the version of torch from 1.7 to 1.4 and then it showed another error like this:

_"02/10/2021 22:40:34 - INFO - __main__ -   ***** Running training *****
02/10/2021 22:40:34 - INFO - __main__ -     Num examples = 100
02/10/2021 22:40:34 - INFO - __main__ -     Num Epochs = 20
02/10/2021 22:40:34 - INFO - __main__ -     Instantaneous batch size per GPU = 16
02/10/2021 22:40:34 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 64
02/10/2021 22:40:34 - INFO - __main__ -     Gradient Accumulation steps = 1
02/10/2021 22:40:34 - INFO - __main__ -     Total optimization steps = 40
Iteration:   0%|                                           | 0/2 [00:06<?, ?it/s]
Epoch:   0%|                                              | 0/20 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 427, in <module>
    main()
  File "main.py", line 384, in main
    loading_info)
  File "main.py", line 124, in train
    dict_ = model(**batch)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/gnn/syntax-augmented-bert/model/syntax_bert.py", line 526, in forward
    linguistic_token_mask=linguistic_token_mask)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/gnn/syntax-augmented-bert/model/syntax_bert.py", line 416, in forward
    seq_len)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/gnn/syntax-augmented-bert/model/graph_encoder.py", line 242, in forward
    dep_rel_emb)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/gnn/syntax-augmented-bert/model/graph_encoder.py", line 266, in forward
    dep_rel_matrix)
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/gnn/syntax-augmented-bert/model/graph_encoder.py", line 295, in forward
    dep_rel_matrix)[0])
  File "/home/yuhai/workspace/anaconda3/envs/syntax-bert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuhai/gnn/syntax-augmented-bert/model/graph_encoder.py", line 381, in forward
    attention_scores = attention_scores + attention_mask
RuntimeError: The size of tensor a (16) must match the size of tensor b (64) at non-singleton dimension 0"_

My environment was built by "pip install -r requirements.txt" and I only changed the version of torch from 1.7 to 1.4 because of the first problem

I wanna ask if the error is from the distribution of some parameters? I would appreciate it if you could find a solution to it.

**Comment by DevSinghSachan** [comment]
Thanks for getting in touch!

From the logs, it looks like there is an error due to multi-gpu usage. Could you try to run the code on 1 GPU and check if this is still the case?
I ran all the experiments on single GPU, and so the code is most tested in that setup.

Best,

**Comment by DevSinghSachan** [comment]
Closing this issue for now due to lack of activity.
